export const CHECK_PAYOUT_REQUEST = "CHECK_PAYOUT_REQUEST";
export const CHECK_PAYOUT_SUCCESS = "CHECK_PAYOUT_SUCCESS";
export const CHECK_PAYOUT_FAIL = "CHECK_PAYOUT_FAIL";

export const NEW_PAYOUT_REQUEST = "NEW_PAYOUT_REQUEST";
export const NEW_PAYOUT_SUCCESS = "NEW_PAYOUT_SUCCESS";
export const NEW_PAYOUT_RESET = "NEW_PAYOUT_RESET";
export const NEW_PAYOUT_FAIL = "NEW_PAYOUT_FAIL";

export const SELLER_PAYOUT_REQUEST = "SELLER_PAYOUT_REQUEST";
export const SELLER_PAYOUT_SUCCESS = "SELLER_PAYOUT_SUCCESS";
export const SELLER_PAYOUT_FAIL = "SELLER_PAYOUT_FAIL";

export const ALL_PAYOUT_REQUEST = "ALL_PAYOUT_REQUEST";
export const ALL_PAYOUT_SUCCESS = "ALL_PAYOUT_SUCCESS";
export const ALL_PAYOUT_FAIL = "ALL_PAYOUT_FAIL";

export const UPDATE_PAYOUT_REQUEST = "UPDATE_PAYOUT_REQUEST";
export const UPDATE_PAYOUT_SUCCESS = "UPDATE_PAYOUT_SUCCESS";
export const UPDATE_PAYOUT_RESET = "UPDATE_PAYOUT_RESET";
export const UPDATE_PAYOUT_FAIL = "UPDATE_PAYOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
